### ISSUE TITLE
Build TDE

### ISSUE THREAD

**Issue by olevenets2** [Ray-V/tde-slackbuilds#6] opened 2018-02-03 09:42 UTC
Hello, this is a good script, but it still lacks some packages: core tdebindings, dependencies-python-tqt, sip4-tqt, tqca, tqscintilla and libraries-libtdeldap, libtqt-perl, mlt, mlt++, pytdeextensions, python-trinity. And just not quite the correct order of the assembly and it seems that the tdm manager does not have enough files for the correct operation.

**Comment by Ray-V** [comment] 2018-02-05 20:49
I've never needed those packages, are you saying you need them, or just want to see them included for completeness? Are you going to submit SlackBuilds for them?

What problems is the build order causing?

I assume tdm is fixed with #7

**Comment by olevenets2** [comment] 2018-02-06 09:24
Yes, this fixes the problem with tdm for this you also need to edit your rc.4 in such a form:

if [ -x /opt/trinity/bin/tdm ]; then
  echo "Using TDM (Trinity Login Manager)."
  echo
log_cleanup "/var/log/tdm.log"
  exec /opt/trinity/bin/tdm -nodaemon -error /var/log/tdm.log
fi

it needs to be added to README or add a separate file to the directory that will create the modified rc.4.new.

As for the order of installing packages according to the trinity wiki, this should look like this, if you install the most complete version:

tqt3 tqtinterface arts dbus-tqt dbus-1-tqt tqca tqca-tls libart-lgpl libcaldav libcarddav sip4-tqt avahi-tqt, tdelibs tdebase.

next comes the support of Python:

tqscintilla python-tqt, python-trinity pytdeextensions

next core:

tdebindings tdeaccessibility tdeutils tdemultimedia tdenetwork tdeadmin tdeartwork tdegames tdetoys tdeedu tdegraphics tdepim tdesdk tdevelop tdeaddons tdewebdev

and libs:

mlt mlt++ libtqt-perl libtdeldap libkexiv2 libkdcraw libkipi libksquirrel kipi-plugins

these packages are needed for a full installation, perhaps not all are necessary for running the environment, but the user can decide to install each package himself.

**Comment by fastname3** [comment] 2018-05-01 18:13
maybe this packages fix the eternal mimetypes error ??

**Comment by Ray-V** [comment] 2018-05-04 13:56
Which ones do you think might do that?

It's been a while since I looked at this - I'll have to go back and see how far I got - but one of the problems seemed to be that TDE recognizes the 'magic' file but ignores its contents.

I think the problem is more to do with what the TDE developers have removed from the various 'mimetypes' source files.

**Comment by Ray-V** [comment] 2018-05-09 22:43
@fastname3
I've found a patch for the mimetypes issue - it's the fix for bug 2713.
I've added it to tdelibs.SlackBuild.
It works for me - hope it works for you.

**Comment by fastname3** [comment] 2018-05-11 23:51
I'm going to try it right now
I'll tell you if it works for me
thanks a lot

**Comment by fastname3** [comment] 2018-05-13 19:51
Hi
tried and recognizes lost txt plaintext binaries scripts and associate icons,
good job :)

but....errors

---tqca-tls is not allowed to compile this is the error:
"tqca-tls.SlackBuild FAILED at line 69"

this is the part of line 69
67-do
68-patch -p0
69-done

if uncomment the lines and try to recompile it gives me another error in line 105

temporal solution: with the old slackbuild of Thorn-Inurcide does not give problems


---tde-base is not allowed to create the *.tgz with this error:
"cp: '/tmp/build/package-tdebase//usr/share/apps/tdm/sessions/tde.desktop' and '/tmp/build/package-tdebase/usr/share/apps/tdm/sessions/tde.desktop' are the same file
tdebase.SlackBuild FAILED at line 118"

this is the part of line 118
116-# Ensure correct login manager session file is available.
117-mkdir -p ${PKG}/usr/share/apps/tdm/sessions
118-cp ${PKG}/${INSTALL_TDE}/share/apps/tdm/sessions/tde.desktop
119-${PKG}/usr/share/apps/tdm/sessions/

temporal solution: can be installed manually from "/tmp/build" where is well compiled.


I'm using to compile updated slackware 14.2 32 bits,
I compiled folder Deps complete, tdelibs and tdebase,
and libcaldav, libcarddav, tdemultimedia, tdegraphics, tdenetwork without kopete section, and knetstat, all without errors

i want to try slackware current but at the moment is impossible all the time he gives me kernel panic in 3 different machines.

it makes me very rare to see all the texts and the scripts with their icons xD
thanks so much

**Comment by Ray-V** [comment] 2018-05-15 16:29
The tdebase error happened because the install directory is /usr, and the error causes an exit 1 which aborts the SlackBuild script.
The simple fix is to append '|| true' as it's an otherwise harmless error.

For the tqca-tls patch problem, see https://github.com/Ray-V/tde-slackbuilds/issues/9#issuecomment-388783249

I'd be very wary about trying to build with the latest Slackware current - the *.la files have been removed and they are used in TDE builds. Read the Slackware current ChangeLog.txt 'Thu Apr 19 01:04:06 UTC 2018' entry for details.

**Comment by olevenets2** [comment] 2018-05-17 11:44
Good job! 

Another problem that I encountered and that I can not solve, polkit-gnome-agent does not start automatically when login TDM and a manual registration fails:

olevenets2 ~ $ /usr/libexec/polkit-gnome-authentication-agent-1

** (polkit-gnome-authentication-agent-1:8242): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: User of caller and user of subject differs.
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: User of caller and user of subject differs.

this is not such a big problem because not everyone needs polkit-gnome-agent, but maybe someone knows how to fix it? I can be wrong, but it seems this may be due to the build parameters of tdelibs or tdebase.

**Comment by olevenets2** [comment] 2018-05-25 17:53
Hi, one more mistake I found is that in Konsole TDE the scrolling of the text (for example in nano) does not work with the mouse wheel. It seems the problem manifests itself on Slackware because at least in Gentoo everything works fine.

**Comment by fastname3** [comment] 2018-06-01 06:46
Hi
all work ok at the moment, better that never

I compiled all this without errors

arts-R14.0.4-i586-1              tdeartwork-R14.0.4-i586-1
dbus-1-tqt-R14.0.4-i586-1        tdeio-locate-R14.0.4-i586-1
dbus-tqt-R14.0.4-i586-1          tdebase-R14.0.4-i586-1
tdegraphics-R14.0.4-i586-1       gtk3-tqt-engine-R14.0.4-i586-1
tdelibkdcraw-R14.0.4-i586-1      kbfx-R14.0.4-i586-1
tdelibs-R14.0.4-i586-1           tdelibkexiv2-R14.0.4-i586-1
kbookreader-R14.0.4-i586-1       tdemultimedia-R14.0.4-i586-2
knetstats-R14.0.4-i586-1         tdenetwork-R14.0.4-i586-1
kshutdown-R14.0.4-i586-1         tdepim-R14.0.4-i586-1
tdetoys-R14.0.4-i586-1           kvpnc-R14.0.4-i586-1
libart_lgpl-R14.0.4-i586-1       tdmtheme-R14.0.4-i586-1
libmp4v2-2.0.0-i586-1            tqca-R14.0.4-i586-1
tde-i18n-es-R14.0.4-noarch-1     tqca-tls-R14.0.4-i586-1
tdeaccessibility-R14.0.4-i586-1     tdeaddons-R14.0.4-i586-1
tqtinterface-R14.0.4-i586-1      tdeadmin-R14.0.4-i586-1
twin-style-crystal-R14.0.4-i586-1     tqt3-R14.0.4-i586-1
tdeutils-R14.0.4-i586-1

only crash in soundconverter, nothing important audacity is more better and work

compiled with updated slackware 14.2 32 bits

personally before compiling I have changed all the routes that point /etc/trinty to /etc/tde

you should put knetstats in apps compile well and it works, checked every day

I have to stick with hal and the bluetooth to see if it works in tde when I have time

thanks a lot

**Comment by Ray-V** [comment] 2018-06-03 19:49
> only crash in soundconverter, nothing important audacity is more better and work

Is that when building it, or running it?

> personally before compiling I have changed all the routes that point /etc/trinty to /etc/tde

I've added a TDE installation directory option '/opt/tde' in the 'gitbuild' branch. I'll look at adding an option for /etc/tde as well.

> you should put knetstats in apps compile well and it works, checked every day

I've added this in the 'gitbuild' branch


Currently doing all revisions/updates/corrections in the 'gitbuild' branch [which includes the R14.0.4 build] - see issue #10. Seems to be working out well, and will merge into 'master' sometime soon hopefully.

**Comment by Ray-V** [comment] 2018-06-10 11:33
> I'll look at adding an option for /etc/tde as well.

Done.

**Comment by fastname3** [comment] 2018-06-11 23:36
soundconverter crash building at first

I always install it in /usr
I do not have more desktops installed so there's no problem with /usr

Once I saw routes to tde and trinity and decided to put everything in tde,
I have everything added if you want I'll give it to you

**Comment by Ray-V** [comment] 2018-06-12 14:13
> I have everything added if you want I'll give it to you

Yes please - I'd like to see what you've done.

**Comment by fastname3** [comment] 2018-06-17 04:03
here it is
If you have problems you will tell me
https://1fichier.com/?z7iv1jdcjo


in BUILD-TDE.sh the order of the apps is changed, all the Misc at the end and something more,
I think the menu is more organized in ncurses like this

added:
ksplash-engine-moodin - dont work
wlassistant - dont work
tqca  - dont work
knetstats - work very well


in some scripts (I do not remember which has been random) I have removed the part of the updates,
There are many scripts with this part repeated:

# Update the desktop database:
if [ -x usr/bin/update-desktop-database ]; then
  chroot . /usr/bin/update-desktop-database ${INSTALL_TDE}/share/applications > /dev/null 2>&1
fi

# Update hicolor theme cache:
if [ -d usr/share/icons/hicolor ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    chroot . /usr/bin/gtk-update-icon-cache -f -t ${INSTALL_TDE}/share/icons/hicolor 1> /dev/null 2> /dev/null
  fi
fi

# Update the mime database:
if [ -x usr/bin/update-mime-database ]; then
  chroot . /usr/bin/update-mime-database ${INSTALL_TDE}/share/mime >/dev/null 2>&1
fi

Once installed doing it by hand would be better,
and then update the caches in each boot with a script.


I have other changes such as this in tdenetwork so it does not compile things that I do not use

    -DBUILD_DCOPRSS="OFF" \
    -DBUILD_DOC="OFF" \
    -DBUILD_FILESHARING="ON" \
    -DBUILD_KDICT="OFF" \
    -DBUILD_TDEDNSSD="ON" \
    -DBUILD_TDEFILE_PLUGINS="ON" \
    -DBUILD_KGET="ON" \
    -DBUILD_KNEWSTICKER="OFF" \
    -DBUILD_KPF="ON" \
    -DBUILD_KPPP="OFF" \
    -DBUILD_KRDC="ON" \
    -DBUILD_KRFB="ON" \
    -DBUILD_KSIRC="OFF" \
    -DBUILD_KTALKD="OFF" \
    -DBUILD_LANBROWSING="OFF" \
    -DBUILD_LIBRSS="OFF" \
    -DBUILD_WIFI="OFF" \
    -DBUILD_KOPETE="OFF" \
    -DBUILD_KOPETE_PROTOCOL_TESTBED="OFF" \
    -DBUILD_KOPETE_PROTOCOL_GROUPWISE="OFF" \
    -DBUILD_KOPETE_PROTOCOL_MSN="OFF" \
    -DBUILD_KOPETE_PROTOCOL_IRC="OFF" \
    -DBUILD_KOPETE_PROTOCOL_OSCAR="OFF" \
    -DBUILD_KOPETE_PROTOCOL_YAHOO="OFF" \
    -DBUILD_KOPETE_PROTOCOL_WINPOPUP="OFF" \
    -DBUILD_KOPETE_PROTOCOL_SMS="OFF" \
    -DBUILD_KOPETE_PROTOCOL_JABBER="OFF" \
    -DBUILD_KOPETE_PROTOCOL_GADU="OFF" \
    -DBUILD_KOPETE_PROTOCOL_MEANWHILE="OFF" \
    -DBUILD_KOPETE_PLUGIN_LATEX="OFF" \
    -DBUILD_KOPETE_PLUGIN_AUTOREPLACE="OFF" \
    -DBUILD_KOPETE_PLUGIN_HISTORY="OFF" \
    -DBUILD_KOPETE_PLUGIN_CONTACTNOTES="OFF" \
    -DBUILD_KOPETE_PLUGIN_CRYPTOGRAPHY="OFF" \
    -DBUILD_KOPETE_PLUGIN_CONNECTIONSTATUS="OFF" \
    -DBUILD_KOPETE_PLUGIN_TRANSLATOR="OFF" \
    -DBUILD_KOPETE_PLUGIN_NOWLISTENING="OFF" \
    -DBUILD_KOPETE_PLUGIN_WEBPRESENCE="OFF" \
    -DBUILD_KOPETE_PLUGIN_TEXTEFFECT="OFF" \
    -DBUILD_KOPETE_PLUGIN_HIGHLIGHT="OFF" \
    -DBUILD_KOPETE_PLUGIN_ALIAS="OFF" \
    -DBUILD_KOPETE_PLUGIN_MOTIONAUTOAWAY="OFF" \
    -DBUILD_KOPETE_PLUGIN_NETMEETING="OFF" \
    -DBUILD_KOPETE_PLUGIN_ADDBOOKMARKS="OFF" \
    -DBUILD_KOPETE_PLUGIN_STATISTICS="OFF" \
    -DBUILD_KOPETE_PLUGIN_SMPPPDCS="OFF" \

but this does not interest anybody anymore, I think it's more personal


Many things are unfinished I just try when I have time,
With a diff program you can see the changes in BUILD-TDE.sh faster

late

**Comment by fastname3** [comment] 2018-06-17 04:06
lol
the bold font are with a # before but here this # is bold font

Update the desktop database:
Update hicolor theme cache:
Update the mime database:

this 3 have a # before not a bold font

**Comment by Ray-V** [comment] 2018-06-18 10:36
> https://1fichier.com/?z7iv1jdcjo

I visited that site and all I got was a load of pop-ups and advertising cr*p

Could you attach that file here please. Github accepts gz and zip compressed files, so I would think that adding that extension to a tar.xz file will be accepted.

**Comment by fastname3** [comment] 2018-06-19 01:13
sorry  I had not seen the attach option here
tar.xz is not accepted pass it to zip

[tde-slackbuilds-retouch.zip](https://github.com/Ray-V/tde-slackbuilds/files/2113475/tde-slackbuilds-retouch.zip)

you need anti-pop-ups xD

**Comment by Ray-V** [comment] 2018-06-22 21:57
Setting sysconfdir is now an option in BUILD-TDE.sh

One thing to look out for is if you select sysconfdir = /etc/tde then the TDEHOME and TDEROOTHOME environment variables have been set to ~/.tde and /root/.tde.
I didn't see any point in having them set to ~/.trinity and /root/.trinity if the configuration files are being placed in /etc/tde. Of course if you don't agree, that can always be commented out.


The 'update' lines are TODO - I don't think they actually cause a problem, just mostly not required ..


ksplash-engine-moodin.SlackBuild you've got    --sysconfdir="/etc/trinity" \
Looks as though the Makefile isn't created if built in an off-root directory. I haven't looked at why, but the attached patch works.


wlassistant.SlackBuild -> cmake build - see attached.


tqca.SlackBuild
I think you have to specify where the libraries are to be installed, assumed to same directory as tqca-tls -> see attached, 


I don't agree with putting the Misc builds at the end.
The build order is the order listed in BUILD-TDE.sh, and where the misc package is a build-time dependency, it needs to go before the app that requires it, and where it's a run-time dependency, it's useful to have that reminder where the app that can use it is selected.

[diffs.zip](https://github.com/Ray-V/tde-slackbuilds/files/2129260/diffs.zip)

**Comment by olevenets2** [comment] 2018-07-02 15:08
I believe that some packages should be renamed to the original name of the source archive (for example, libart_lgpl replaces a system one, which may be unacceptable for some cases) and this would be more correct than it is now.

**Comment by fastname3** [comment] 2018-07-07 07:05
I only follow the build order in Base and Deps

good the new options en ncurses menu and the new attach

but...

tdebase-R14.0.4 and cgit fail to compile, the rest is ok till tdebase

end of log:

[ 47%] Built target tdeinit_konsole-shared
error Makefile:127
make: *** [all] Error 2

**Comment by Ray-V** [comment] 2018-07-08 13:15
@fastname3

I've just done a tdebase cgit build for x86_64 with gcc to commit 967cf908 and it completed without errors, and R14.0.4 from the tarball builds OK.

To be able to help you, I'll need more information - start with the actual error output in the log file - it usually shows as 'error: '

**Comment by olevenets2** [comment] 2018-07-11 22:16
Hi, when compiling the package tqt3 i see a log error:

`error while loading shared libraries: libtqt-mt.so.3: cannot open shared object file: No such file or directory`

this may be due to incorrect configurations ./configure \ or to LD_LIBRARY_PATH and needs to be fixed. Also I see other errors:

> clang-3.8: error: no such file or directory: 'qmake_image_collection.cpp'
> clang-3.8: error: no input files
> 
> formwindow.cpp:42:10: [0;1;31mfatal error: 'connectiondialog.h' file not found
> In file included from mainwindow.cpp:43:
> In file included from ./propertyeditor.h:48:
> ./hierarchyview.h:167:10: [0;1;35mwarning: 'FormDefinitionView::setCurrent' hides
>       overloaded virtual function [-Woverloaded-virtual]
>     void setCurrent( TQWidget *w );
> 
> In file included from command.cpp:42:
> ./actioneditorimpl.h:37:10: [0;1;31mfatal error: 'actioneditor.h' file not found
> #include "actioneditor.h"
> 
> mainwindowactions.cpp:61:10: [0;1;31mfatal errorIn file included from mainwindow.cpp:47:
> ./newformimpl.h:37:10: [0;1;31mfatal error: 'newform.h' file not found 

and so on. That may be associated with this and should be checked after fixing the build script. In the script that I posted above there are no such errors when compiling, you can check the configuration from there.

Also I do not see the full localization in the menu of the user's session termination for the cgit-packages, only a part of the options has a translation, this may be due to the incorrect operation of the localization script and needs to be checked.

**Comment by fastname3** [comment] 2018-07-12 12:45
I only compile in 32 bits i dont know if work ok in 64 bits

if you want i can send all log complete, this leave send logs archives

the compilation with cgit send the number of TDE version 14.1.0
but a new iso of pclinuxos with tde send version 14.0.5 Dev
only a curiosity comment

olevenets2 i believe you have a bad GCC, try to uodate.

**Comment by Ray-V** [comment] 2018-07-13 09:46
@fastname3

A 32 bit build completes for me.

For a cgit build, I actually got a build error on tqt3, so I removed all *R14.0.4* packages from the build environment.

I suggest you do the same, including removing the cgit packages you've already built and installed. <a href="#issuecomment-393779239">You've previously reported a successful build</a>, so it's possible that previously installed packages are causing the problem.

I think I need to add a note about this in BUILD-TDE.sh - not to mix R14.0.4 and cgit builds in the same build environment. [ @olevenets2 I think this might be causing your tqt3 build error. ]

If the build still fails, then attach the tdebase-build-log and CMakeOutput.log [from /tmp/build/tmp-tdebase/tdebase/build-tdebase/CMakeFiles/].

**Comment by Ray-V** [comment] 2018-07-13 09:54
@olevenets2

> Also I do not see the full localization in the menu of the user's session termination for the cgit-packages, only a part of the options has a translation, this may be due to the incorrect operation of the localization script and needs to be checked.

I don't know what this means. Could you add some more detail please.

**Comment by olevenets2** [comment] 2018-07-13 16:33
I compile tqt3 in a "clean" environment, this can not be due to other tde packages in the system. it's some kind of error with finding libraries in the script. I'll attach my log, maybe this will help.
[tqt3-build-log.gz](https://github.com/Ray-V/tde-slackbuilds/files/2193478/tqt3-build-log.gz)

**Comment by fastname3** [comment] 2018-07-14 02:44
maybe make 2 versions cgit and R14.0.4 is better,
cgit version will be forever and the other according to realesed,
so R14.0.4 should expire soon.

i removed all, cgit packages are changing and updating over time I think I should be like that,
i install slackware millions of times i like start from zero, I have a HD just to compile tde.

I had no problems with tqt3 only with base at the end :(

maybe some tdebase from the trinity repository were wrong,
tdebase are update from 10 days ago so I will try from cgit in a few days and I will tell you something

**Comment by fastname3** [comment] 2018-07-18 20:17
i have a doubt Ray-V 
you complete compilation from git without errors how do you do it
slackware 14-2 clean?
slackware 14-2 update?
or
slackware current?

I usually use slackware 14-2 update

**Comment by Ray-V** [comment] 2018-07-21 11:41
@olevenets2 - now I see what you mean - I thought the build was failing.

My view on this is that tqt3 is only used to provide TDE run-time support and as built here it does do that. For that reason, I don't see a problem with the error messages, which I also get.

You're probably right that the reason these errors don't appear in the other build is because of the configure options.

If you want to alter the build script to include the functionality in tqt3 that these errors are preventing, then please update the tqt3.SlackBuild and attach it here or submit a pull request. We can then see what affect this has on the final package and I can then set an option in BUILD-TDE.sh to choose whether to do a full build or not.

**Comment by Ray-V** [comment] 2018-07-21 11:51
@fastname3

I build both 32 bit and 64 bit on the same machine in chroots, so the 32 bit build is done with a 64 bit kernel.

I've only used Slackware 14.2 for the Raspbery Pi soft float build and I remember gcc 5.3 causing build problems so I built gcc 5.4.0 for that, and decided that Sl14.2 was too much effort to maintain.

My chroot build environment is not at any particular Slackware version. It's a partial update to Slackware current but I haven't kept it completely up-to-date because it's only used to build TDE, which it does successfully, and I don't want to mess that up.

For example:
As you're using 14.2 update, I assume you're using gcc-5.5.0/glibc-2.23
I'm using gcc-5.4.0/glibc-2.25

Why don't you attach your build logs so we can see what the errors are?

**Comment by fastname3** [comment] 2018-07-21 20:32
Yes I use gcc-5.5.0/glibc-2.23
I'm going to try with gcc-8.1.1/glibc-2.27 from current in the next compilation,

when I do I attach not worry now I'm busy with other things
and it's very hot this summer and it takes away the desire to reheat the machine xDD

**Comment by olevenets2** [comment] 2018-07-25 16:00
**Ray-V**, I do not know yet what exactly needs to be changed in the script to properly link the libtqt-mt.so library. if you know this, make a change to the script.

**Comment by fastname3** [comment] 2018-07-27 20:32
at the end with a slackware without updating (32bits) I was able to compile from cgit a desktop that works,
I also install compiz with elastic windows cube animations and all that is compiz,
I wanted to attach here 2 captures (.png) with trinity new dev version and compiz working but nothing goes up, the attach option here with *.png dont work for me,
so I have uploaded them here:
https://s8.hostingkartinok.com/uploads/images/2018/07/15df8186dd56bd0d29d3d48ae3e97099.png
https://s8.hostingkartinok.com/uploads/images/2018/07/530b1c80e9a80ba04bde8bfa8c58e3be.png
dont fear no pop-ups or advertisings they will attack you xDD

many red fatal errors in the compilation but it works,
tde-network was impossible to compile, error in line 49
after compile the desktop base I wanted to compile more and it did not give me internet access, I did not find connection,
I have to try better and I'll keep all logs
I'm thinking of updating slackware or only D section or not.

**Comment by Ray-V** [comment] 2018-07-29 13:49
@fastname3 

> the attach option here with *.png dont work for me,

You could have put them in a 'zip' archive

> dont fear no pop-ups or advertisings they will attack you xDD

Didn't give them a chance, I used wget to download

> many red fatal errors in the compilation but it works,

Is this what olevenets2 is complaining about in the tqt3 build?

> tde-network was impossible to compile, error in line 49

This just tells me that cmake failed, what was the actual error - the 'error: ' output in the logs

> I'm thinking of updating slackware or only D section or not.

I've now set up 32-bit and 64-bit chroots of Slackware-current and the Required packages and tdenetwork build.

**Comment by fastname3** [comment] 2018-08-01 03:05
much fatal errors but at the end it works
the code of trinity stop being prepared a long time ago for slackware there will always be mistakes
if you compile trinity in debian may be you do not have any error, or less
thanks that works in slack not only with the sectarians of debian

also git version is sometimes slow and does not detect me well the devices on the fly, external hd etc
routes to git fail a lot too,
I prefer to use the 14.0.4 at the moment

there are no more errors the whole log of tde-network is this
error in line 49
no more
it's something about a route and quotes
I changed it but I have not had time to try it

you know when the new trinity ending comes out??
and slackware? they are not good about money

good luck

**Comment by fastname3** [comment] 2018-08-01 03:13
I like the new tdehwdevicetray,
you know if you can put in 14.0.4??
the code is from 2015
regards

**Comment by Ray-V** [comment] 2018-08-05 14:37
@olevenets2

For the tqt3 build as it is now, tquic looks in the usual places for libraries, including that set by its RPATH, which is derived from the library path set in the build script, for example:

<pre> # readelf -d /tmp/build/tmp-tqt3/tqt3/bin/tquic
  .. snip ..
 (RPATH)    Library rpath: [/opt/tde/lib64/tqt3-cgit/lib]
</pre>
That will only be populated after tqt3 has been installed, so during the first make none of the directories in the tquic library search path contain libtqt-mt.so.3.
And I suspect it is the reason why the 'make/make install' lines in the SlackBuild are repeated - so that during the second make, after the libs have been installed in /opt/tde/lib64/tqt3-cgit/lib, tquic **can** find libtqt-mt.so.3

Setting LD_LIBRARY_PATH to the build libs directory should allow tquic to find libtqt-mt.so.3 during the first make, but it doesn't. I don't know why, but suspect it has something to do with the build environment.

But that doesn't matter, because there is a better solution, which is to set the RPATH in tquic relative to its origin. That suits us because we are building and installing into different directories.

From the ld.so man page:

>ld.so understands the string $ORIGIN ... in an rpath specification ... to mean the directory containing the application executable. Thus, an application located in somedir/app could be compiled with gcc -Wl,-rpath,'$ORIGIN/../lib' so that it finds an associated shared library in somedir/lib no matter where somedir is located in the directory hierarchy.

We have that directory structure in tqt3 where the bin and lib directories always share the same root.
So by setting
<pre> (RPATH)    Library rpath: [$ORIGIN/../lib]</pre>
for tquic, it will always find libtqt-mt.so.3 whether it's during the build or at run-time.

This is done with the tqt3 configure '-R' option. This has been used in the script you posted, except it adds the temporary build directory to the RPATH. I haven't built it, but think it would look like this:
<pre> (RPATH)    Library rpath: [/tmp/build/tmp-tqt3/tqt3/lib:/opt/tde/lib64/tqt3-cgit/lib]</pre>

That will work because at run-time the /tmp/.../lib directory won't exist and tquic will find the libtqt-mt.so.3 library it needs in /opt/tde/lib64/tqt3-cgit/lib. But that retains the temporary build directory.

Using
<pre> -R-Wl,-rpath,\'\\\$\$ORIGIN/../lib\'</pre>
as a configure option for tqt3 works for both the build and run-time. The excessive escaping is necessary to ensure that $ORIGIN is not evaluated.
There is then no need to run 'make/make install' a second time, and no need to set LD_LIBRARY_PATH, so they have been removed from the SlackBuild.

```diff
--- Deps/tqt3/tqt3.SlackBuild
+++ Deps/tqt3/tqt3.SlackBuild
@@ -38,0 +39,3 @@
+## don't waste time building tutorial and examples
+sed -i 's|sub-tutorial sub-examples||' Makefile
+
@@ -40,0 +44,4 @@
+
+## $ORIGIN/../lib is to be added to RPATH, so don't need this option:
+sed -i "s|QMAKE_RPATH.*$|QMAKE_RPATH =|" mkspecs/linux-g++/qmake.conf
+
@@ -97 +104,2 @@
- -plugin-style-windows
+ -plugin-style-windows \
+ -R-Wl,-rpath,\'\\\$\$ORIGIN/../lib\'
@@ -100,4 +107,0 @@
-QTDIR=$PKG$TQTDIR-$VERSION
-LD_LIBRARY_PATH=$QTDIR/lib make install INSTALL_ROOT=$PKG || exit 1
-
-make -i $NUMJOBS symlinks sub-src sub-tools || exit 1
```

**Comment by fastname3** [comment] 2018-08-06 07:06
the other day the git was updated and tried to compile a new compilation sure
and everything go well I was able to compile almost everything until rosegarden too
I think the gif goes when he wants or not

I went crazy looking for the hal DWITH I did not know you taken it,
tried compile with hal support but it did not work

What does it mean in changelog
"No longer maintained"
you do not follow with this??

regards

**Comment by fastname3** [comment] 2018-08-20 04:01
It has happened to me a few times

sometimes few not always /tmp/tde-root not clean the tmp cache archives as it should, they accumulate and crash the system for not leaving space in root,
if i am fast and the files are cleaned manually before everything crash can be recovered the system,
if not i must restart all forced by the bad
This is fucked up for me because I use a live linux and all the work is lost when all crash

Has it happened to someone else or just me?
it will be the fault of being live linux?
It can be fixed?

regards

**Comment by fastname3** [comment] 2018-08-20 05:34
2018.08.18: Trinity Desktop Environment R14.0.5 Released!
but the official packages or iso lives to date are still not on any server

**Comment by Ray-V** [comment] 2018-08-22 08:46
I don't think the problem is a live system. I use an updated Slax v7 which is effectively a live system and the temporary build data clears every time.

Attach your modified scripts here and I'll run them to see if I can reproduce the problem.

---------------

I'm waiting for the R14.0.5 sources to be uploaded. I don't expect any major problems because basically R14.0.5 will be what was in cgit. When I've run a successful build I'll update the scripts here.

**Comment by fastname3** [comment] 2018-08-23 23:56
slax 7 is debian i use slackware

what modified scripts??
modified only this in tdebase.SlackBuild
    -DWITH_HAL="ON" \
hal and trinity is a global problem I read in forums
must be compiled hal very very special the slackware package dont work
no packages work only a compilation with trirnity variables or like this
is complicated for me

dont clear big files like movies with 2 Gb or more, only this,

yes basically cgit, no hurry

**Comment by SlavekB** [comment] 2018-08-24 07:11
Slax before version 9.x was based on Slackware. On Debian is based Slax versions >= 9.x.

Mentioned Slax 7 is therefore a version that was based on Slackware.

**Comment by Ray-V** [comment] 2018-08-24 22:14
@fastname3

I thought you'd altered BUILD-TDE.sh to add some packages and move the misc builds to the end, and that maybe there was a typo causing a problem.

The sequence for removing the build data starts in BUILD-TDE.sh. In the 'Temporary Build Files' screen the answer should be 'No'. This echoes 'no' to /tmp/build/vars/KEEP_BUILD.

That is then set in a variable and tested in get-source.sh with:

[[ $KEEP_BUILD != "yes" ]] && echo -e "\n removing previous build data ..\n" && rm -rf $TMP_BUILD/{tmp,package}*

So if you're setting this to 'No', the build directories should be deleted before the next package is built.

If this isn't happening, have you got 'rm' set interactively, or aliased to something else?

**Comment by fastname3** [comment] 2018-09-06 02:23
yes SlavekB Slax 7 is based on Slackware slax 9 in debian but I did not think I would use something so old,

Ray-V nothing of that it is not the problem it is once everything is installed,
only happens playing or moving large videos of more than 1 gig
but as I know, I'm watching it manually delete it before crash all
the lives have less space in root and it fills up fast but should be deleted alone
nothing to do with the compilation

I've seen the new build R14.0.5 when I can I will prove it
thanks for all

**Closed as completed** 2018-11-23 11:45 UTC
